# Generated by Django 5.0.1 on 2024-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
