# Generated by Django 5.0.1 on 2024-02-03 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_observation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatheralert",
            name="location",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="WeatherAlert",
        ),
    ]
