# Generated by Django 5.0 on 2023-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hellcar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="brand_logos/"),
        ),
    ]
